CDStore/Models/CDObject.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CDStore.Models
{
    public class CDObject
    {
        [Required(ErrorMessage = "Please enter a Bank.")]
        public string Bank { get; set; }
        [Required(ErrorMessage = "Please enter a Term.")]
        public int? Term { get; set; }
        [Required(ErrorMessage = "Please enter a Rate.")]
        public double? Rate { get; set; }
        [Required(ErrorMessage = "Please enter a PurchaseDate.")]
        public DateTime? PurchaseDate { get; set; }
        [Required(ErrorMessage = "Please enter a DepositAmount.")]
        public double? DepositAmount { get; set; }

        public DateTime? MaturityDate
        {
            get
            {
                if (PurchaseDate.HasValue && Term.HasValue)
                {
                    return PurchaseDate.Value.AddMonths(Term.Value);
                }
                else
                {
                    return null;
                }
            }
        }


        //https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator
        //You didn't specify formula, so I did what I thought was correct.
        public double? MaturityValue
        {
            get
            {
                if (DepositAmount.HasValue && Rate.HasValue && Term.HasValue)
                {
                    return DepositAmount.Value * Math.Pow(1 + (Rate.Value / 100), (Term.Value/12));

                }
                else
                {
                    return null;
                }
            }
        }

        public CDObject()
        {

        }
        public CDObject(string bank, int term, double rate, DateTime purchaseDate, double depositAmount)
        {
            Bank = bank;
            Term = term;
            Rate = rate;
            PurchaseDate = purchaseDate;
            DepositAmount = depositAmount;

        }
    }
}

CDStore/Models/Repository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CDStore.Models
{
    public class Repository
    {
        private static List<CDObject> cdLines = new List<CDObject>();

        public static IEnumerable<CDObject> showLines
        {
            get
            {
                return cdLines;
            }
        }

        public static void AddResponse(CDObject cdObject)
        {
            cdLines.Add(cdObject);
        }
    }
}

CDStore/Controllers/MainController.cs
using CDStore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CDStore.Controllers
{
    public class MainController : Controller
    {
        public ViewResult Index()
        {
            //CDObject test = new CDObject("Test", 60, 5.00, DateTime.Parse("9/18/2017"), 1000);
            /*CDObject test1 = new CDObject("Test", 12, 2.00, DateTime.Parse("9/18/2017"), 20000);*/

/*            List<CDObject> list = new List<CDObject>();
            list.Add(test);
            list.Add(test1);*/

            ViewBag.listEmpty = !Repository.showLines.Any<CDObject>();

            return View("Index", Repository.showLines);
            //return View("Index", list);
        }

        [HttpGet]
        public ViewResult AddCD()
        {
            return View();
        }

        [HttpPost]
        public ViewResult AddCD(CDObject data)
        {

            if (ModelState.IsValid)
            {
                Repository.AddResponse(data);
                return Index();
            }
            else
            {
                return View();
            }
        }
    }
}

CDStore/Views/Main/AddCD.cshtml
@model CDStore.Models.CDObject;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/styles.css" runat="server" />

    <style>
        body {
            border: 2px solid black;
            border-radius: 10px;
            padding: 15px;
            margin: 0 auto;
            border: 2px solid black;
            border-radius: 10px;
            height: fit-content;
            width: 800px;
        }

        label {
            font-weight: bold;
        }
    </style>
</head>

<title>Add a CD</title>

</html>

<body>
    <div class="panel panel-success">
        <div class="panel-heading text-center"><h3>Add a CD</h3></div>
        <div class="panel-body">
            <form asp-action="AddCD" method="post">
                <div asp-validation-summary="All"></div>

                <div class="form-group">
                    <label>Bank:</label>
                    <select class="form-control" asp-for="Bank">
                        <option value="">Choose a Bank</option>
                        <option value="UWCU">UWCU</option>
                        <option value="Wells Fargo">Wells Fargo</option>
                        <option value="Chase">Chase</option>
                    </select>
                </div>


                <div class="form-group">
                    <label>Term (Months):</label>
                    <select class="form-control" asp-for="Term">
                        <option value="">Choose a Term</option>
                        <option value="12">12</option>
                        <option value="24">24</option>
                        <option value="48">48</option>
                        <option value="60">60</option>
                    </select>
                </div>

                <div class="form-group">
                    <label asp-for="Rate">Rate (%):</label>
                    <input type="number" class="form-control" asp-for="Rate" />
                </div>

                <div class="form-group">
                    <label asp-for="DepositAmount">Deposit Amount:</label>
                    <input type="number" class="form-control" asp-for="DepositAmount" />
                </div>

                <div class="form-group">
                    <label asp-for="PurchaseDate">Purchase Date:</label>
                    <input type="date" class="form-control" asp-for="PurchaseDate" />
                </div>



                <button class="btn btn-success" type="submit">Add CD</button>
                <a class="btn btn-secondary" asp-action="Index">Back</a>


            </form>
        </div>

    </div>
</body>


CDStore/Views/Main/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model IEnumerable<CDStore.Models.CDObject>

    <html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <style>

            body {
                border: 5px solid black;
                border-radius: 10px;
                padding: 15px;
                margin: 0 auto;
                border: 2px solid black;
                border-radius: 10px;
                height: fit-content;
                width: 1000px;
            }

            .addCD {
                margin: 20 0px;
                color: white !important;
            }
        </style>
    </head>

    <title>My CD Portfolio</title>

</html>

<body>

    <h1>My CD Portfolio</h1>

    @if(@ViewBag.listEmpty) {

    <div>
        <h2>
            No CDs currently in the portfolio.
        </h2>
        <a class="btn btn-primary" asp-action="AddCD">Add CD</a>
    </div>

    } else {

    <a class="btn btn-primary addCD" asp-controller="Main" asp-action="AddCD">Add CD</a>

    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Bank</th>
                <th>Term (Months)</th>
                <th>Rate</th>
                <th>Purchase Date</th>
                <th>Maturity Date</th>
                <th>Deposit Amount</th>
                <th>Value at Maturity</th>
            </tr>
        </thead>
        <tbody>
            @foreach (CDStore.Models.CDObject r in Model)
            {
            <tr>
                <td>@r.Bank</td>
                <td>@r.Term</td>
                <td>@r.Rate</td>
                <td>@r.PurchaseDate</td>
                <td>@r.MaturityDate</td>
                <td>@r.DepositAmount</td>
                <td>@r.MaturityValue</td>
            </tr>
            }
        </tbody>
    </table>
    }

</body>
